### ISSUE TITLE
Error when clicking on a date

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/InNoHassle-MusicRoomBot#19]
```
2024-01-24T22:44:07.911867282Z Traceback (most recent call last):
2024-01-24T22:44:07.911878082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 308, in _process_update
2024-01-24T22:44:07.911887082Z     response = await self.feed_update(bot, update, **kwargs)
2024-01-24T22:44:07.911895582Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.911904082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
2024-01-24T22:44:07.911912882Z     response = await self.update.wrap_outer_middleware(
2024-01-24T22:44:07.911921982Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.911930082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
2024-01-24T22:44:07.911939082Z     return await handler(event, data)
2024-01-24T22:44:07.911947682Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.911956082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
2024-01-24T22:44:07.911966682Z     return await handler(event, data)
2024-01-24T22:44:07.911975282Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.911984082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
2024-01-24T22:44:07.911992982Z     return await handler(event, data)
2024-01-24T22:44:07.912002282Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912011182Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/manager/manager_middleware.py", line 77, in __call__
2024-01-24T22:44:07.912020482Z     return await handler(event, data)
2024-01-24T22:44:07.912029082Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912037782Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
2024-01-24T22:44:07.912047282Z     return await wrapped_inner(event, kwargs)
2024-01-24T22:44:07.912055982Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912064782Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
2024-01-24T22:44:07.912074482Z     return await wrapped()
2024-01-24T22:44:07.912083282Z            ^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912091882Z   File "/code/src/main.py", line 38, in _listen_update
2024-01-24T22:44:07.912100782Z     res = await super()._listen_update(update, **kwargs)
2024-01-24T22:44:07.912109882Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912121282Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 275, in _listen_update
2024-01-24T22:44:07.912131482Z     return await self.propagate_event(update_type=update_type, event=event, **kwargs)
2024-01-24T22:44:07.912153782Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912162882Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
2024-01-24T22:44:07.912174282Z     return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
2024-01-24T22:44:07.912182382Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912190982Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/context/intent_middleware.py", line 156, in process_callback_query
2024-01-24T22:44:07.912199782Z     return await handler(event, data)
2024-01-24T22:44:07.912208482Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912217282Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/manager/manager_middleware.py", line 77, in __call__
2024-01-24T22:44:07.912226282Z     return await handler(event, data)
2024-01-24T22:44:07.912234782Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912243382Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
2024-01-24T22:44:07.912252682Z     return await self._propagate_event(
2024-01-24T22:44:07.912261082Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912269682Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
2024-01-24T22:44:07.912279082Z     response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
2024-01-24T22:44:07.912288082Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912298182Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
2024-01-24T22:44:07.912307482Z     return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
2024-01-24T22:44:07.912316282Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912324982Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
2024-01-24T22:44:07.912334082Z     return await self._propagate_event(
2024-01-24T22:44:07.912342482Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912351182Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
2024-01-24T22:44:07.912361682Z     response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
2024-01-24T22:44:07.912370882Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912380082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
2024-01-24T22:44:07.912389182Z     return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
2024-01-24T22:44:07.912408882Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912418282Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
2024-01-24T22:44:07.912427582Z     return await self._propagate_event(
2024-01-24T22:44:07.912436282Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912445082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
2024-01-24T22:44:07.912454482Z     response = await observer.trigger(event, **kwargs)
2024-01-24T22:44:07.912463182Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912472082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
2024-01-24T22:44:07.912481982Z     return await wrapped_inner(event, kwargs)
2024-01-24T22:44:07.912490482Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912498982Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/manager/manager_middleware.py", line 52, in __call__
2024-01-24T22:44:07.912508282Z     return await handler(event, data)
2024-01-24T22:44:07.912516782Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912525782Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/context/intent_middleware.py", line 168, in context_saver_middleware
2024-01-24T22:44:07.912535182Z     result = await handler(event, data)
2024-01-24T22:44:07.912543582Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912551982Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
2024-01-24T22:44:07.912561182Z     return await wrapped()
2024-01-24T22:44:07.912607782Z            ^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912617082Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/dialog.py", line 149, in _callback_handler
2024-01-24T22:44:07.912626582Z     await dialog_manager.show()
2024-01-24T22:44:07.912648182Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/manager/manager.py", line 295, in show
2024-01-24T22:44:07.912658082Z     new_message = await self.dialog().render(self)
2024-01-24T22:44:07.912666982Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912677482Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/dialog.py", line 123, in render
2024-01-24T22:44:07.912687182Z     new_message = await window.render(self, manager)
2024-01-24T22:44:07.912695982Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912704982Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/window.py", line 98, in render
2024-01-24T22:44:07.912714182Z     current_data = await self.load_data(dialog, manager)
2024-01-24T22:44:07.912734682Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912743282Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/window.py", line 75, in load_data
2024-01-24T22:44:07.912753182Z     data.update(await self.getter(**manager.middleware_data))
2024-01-24T22:44:07.912761782Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912770582Z   File "/opt/pysetup/.venv/lib/python3.11/site-packages/aiogram_dialog/widgets/data/data_context.py", line 37, in __call__
2024-01-24T22:44:07.912780082Z     return await self.normal_getter(
2024-01-24T22:44:07.912788682Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-24T22:44:07.912797282Z   File "/code/src/routers/booking/create_booking_routes.py", line 105, in getter_for_time_selection
2024-01-24T22:44:07.912806682Z     data["remaining_daily_hours_hours"] = int(hours)
2024-01-24T22:44:07.912815882Z                                           ^^^^^^^^^^
2024-01-24T22:44:07.912824282Z TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by ArtemSBulgakov** [comment]
Fixed by restarting API container
